package com.foodstore.util.constraints;

import com.foodstore.model.entity.Customer;

public class MailConstraints {
	// Replace with your email here:  
    public static final String MY_EMAIL = "foodstoredatn2022@gmail.com";

    // Replace password!!
    public static final String MY_PASSWORD = "bktohzbdbzfzkfyf";

    // And receiver!
    public static final String FRIEND_EMAIL = "lucduong3k@gmail.com";
    
    public static String EmailRegister(Customer customer) {
		return "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #f1f1f1; margin: 0 auto; padding: 0; height: 100%; width: 100%;\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 375px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 414px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : END -->\r\n"
				+ "\r\n"
				+ "    <!-- Progressive Enhancements : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "@media screen and (max-width: 500px) {}\r\n"
				+ "</style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #f1f1f1; font-family: 'Lato', sans-serif; font-weight: 400; font-size: 15px; line-height: 1.8; color: rgba(0,0,0,.4); mso-line-height-rule: exactly; background-color: #f1f1f1; margin: 0 auto; height: 100%; width: 100%; padding: 0;\">\r\n"
				+ "	<center style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; display: none; font-size: 1px; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "      	<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"top\" class=\"bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; padding: 1em 2.5em 0 2.5em; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "          	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "          		<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          			<td class=\"logo\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-align: center; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" align=\"center\">\r\n"
				+ "			            <h1 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; color: #000000; margin-top: 0; font-weight: 400; margin: 0;\"><a href=\"#\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; color: #30e3ca; font-size: 24px; font-weight: 700; font-family: 'Lato', sans-serif;\">FOODSTORE</a></h1>\r\n"
				+ "			          </td>\r\n"
				+ "          		</tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; position: relative; z-index: 0; padding: 3em 0 2em 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <img src=\"https://www.washingtonian.com/wp-content/uploads/2020/01/100Best-scaled.jpg\" alt=\"\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; -ms-interpolation-mode: bicubic; width: 300px; max-width: 600px; height: auto; margin: auto; display: block;\" width=\"300\">\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "				<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; position: relative; z-index: 0; padding: 2em 0 4em 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <table style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "            	<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "            		<td style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            			<div class=\"text\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: rgba(0,0,0,.3); padding: 0 2.5em; text-align: center;\">\r\n"
				+ "            				<h2 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; margin-top: 0; color: #000; font-size: 40px; margin-bottom: 0; font-weight: 400; line-height: 1.4;\">Welcome #"+customer.getId()+" - "+customer.getUsername()+" to FOODSTORE</h2>\r\n"
				+ "            				<h3 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; color: #000000; margin-top: 0; font-size: 24px; font-weight: 300;\">To use our utilities please activate your account</h3>\r\n"
				+ "            				<p style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><a href=\""+"http://localhost:8080/security/verify-email/"+customer.getCode()+"\" class=\"btn btn-primary\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; padding: 10px 15px; display: inline-block; border-radius: 5px; background: #30e3ca; color: #ffffff;\">Verify your email</a></p>\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}
    
    public static String EmailRegisterSubject(Customer customer) {
    	return "Confirm your email account "+customer.getUsername().toUpperCase();
    }
    
    public static String EmailForgot(String code,String username,Long id) {
		return "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #f1f1f1; margin: 0 auto; padding: 0; height: 100%; width: 100%;\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 375px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "  u ~ div .email-container {\r\n"
				+ "    min-width: 414px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : END -->\r\n"
				+ "\r\n"
				+ "    <!-- Progressive Enhancements : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "@media screen and (max-width: 500px) {}\r\n"
				+ "</style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #f1f1f1; font-family: 'Lato', sans-serif; font-weight: 400; font-size: 15px; line-height: 1.8; color: rgba(0,0,0,.4); mso-line-height-rule: exactly; background-color: #f1f1f1; margin: 0 auto; height: 100%; width: 100%; padding: 0;\">\r\n"
				+ "	<center style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; display: none; font-size: 1px; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "      	<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"top\" class=\"bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; padding: 1em 2.5em 0 2.5em; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "          	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "          		<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          			<td class=\"logo\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-align: center; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" align=\"center\">\r\n"
				+ "			            <h1 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; color: #000000; margin-top: 0; font-weight: 400; margin: 0;\"><a href=\"#\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; color: #30e3ca; font-size: 24px; font-weight: 700; font-family: 'Lato', sans-serif;\">FOODSTORE</a></h1>\r\n"
				+ "			          </td>\r\n"
				+ "          		</tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; position: relative; z-index: 0; padding: 3em 0 2em 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <img src=\"https://www.washingtonian.com/wp-content/uploads/2020/01/100Best-scaled.jpg\" alt=\"\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; -ms-interpolation-mode: bicubic; width: 300px; max-width: 600px; height: auto; margin: auto; display: block;\" width=\"300\">\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "				<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #ffffff; position: relative; z-index: 0; padding: 2em 0 4em 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <table style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0; border-collapse: collapse; table-layout: fixed; margin: 0 auto;\">\r\n"
				+ "            	<tr style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">\r\n"
				+ "            		<td style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            			<div class=\"text\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: rgba(0,0,0,.3); padding: 0 2.5em; text-align: center;\">\r\n"
				+ "            				<h2 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; margin-top: 0; color: #000; font-size: 40px; margin-bottom: 0; font-weight: 400; line-height: 1.4;\">Account #"+id+" - "+username+" requested to change new password</h2>\r\n"
				+ "            				<h3 style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; color: #000000; margin-top: 0; font-size: 24px; font-weight: 300;\">Click the link below to create a new password</h3>\r\n"
				+ "            				<p style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><a href=\""+"http://localhost:8080/security/change/"+code+"\" class=\"btn btn-primary\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; padding: 10px 15px; display: inline-block; border-radius: 5px; background: #30e3ca; color: #ffffff;\">Change your password</a></p>\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}
    
    public static String EmailForgotSubject(String username) {
    	return "Request to change password account "+username.toUpperCase();
    }
}
